### ISSUE TITLE
 error: 'CURLOPT_XFERINFOFUNCTION' undeclared

### ISSUE THREAD

**Issue by theory** [pramsey/pgsql-http#62]
Trying to build on CentOS 7.4.1708, where libcurl is at v7.29.0, I get:

```
In file included from /usr/include/curl/curl.h:2227:0,
                 from http.c:69:
http.c: In function 'http_request':
http.c:842:29: error: 'CURLOPT_XFERINFOFUNCTION' undeclared (first use in this function)
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
                             ^
http.c:842:2: note: in expansion of macro 'CURL_SETOPT'
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
  ^
http.c:842:29: note: each undeclared identifier is reported only once for each function it appears in
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
                             ^
http.c:842:2: note: in expansion of macro 'CURL_SETOPT'
  CURL_SETOPT(g_http_handle, CURLOPT_XFERINFOFUNCTION, http_progress_callback);
  ^
make: *** [http.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.S40Dcu (%build)
```

It looks like [CURLOPT_XFERINFOFUNCTION](https://curl.haxx.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html) was added in v7.32.0, but your README says pgsql-http requires 7.20.0 or higher. So I guess increment the minimum required version of libcurl or drop the use of this function?

**Comment by theory** [comment]
Thanks!
